openapi: 3.0.1
info:
  title: Dynamics Account Management API
  contact:
    name: API Team
    url: https://github.com/bcgov/maltd
    email: apiteam@example.org
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
paths:
  /api/projects:
    get:
      tags:
        - Projects
      summary: Gets the list of available projects.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /api/users:
    get:
      tags:
        - Users
      summary: Searches for a user.
      parameters:
        - name: q
          in: query
          description: The username to search for.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  "/api/users/{username}":
    get:
      tags:
        - Users
      summary: Gets a user
      parameters:
        - name: username
          in: path
          description: The username to get
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetailedUser"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
          description: The id of the project
          nullable: true
        name:
          type: string
          description: The name of the project
          nullable: true
        type:
          type: string
          description: The type of project, ie Dynamics or SharePoint
          nullable: true
      additionalProperties: false
      description: Represents a project that a user can be granted access to.
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    User:
      type: object
      properties:
        id:
          type: string
          description: ""
          nullable: true
        username:
          type: string
          description: ""
          nullable: true
        enabled:
          type: boolean
          description: ""
          nullable: true
        firstName:
          type: string
          description: ""
          nullable: true
        lastName:
          type: string
          description: ""
          nullable: true
        email:
          type: string
          description: ""
          nullable: true
      additionalProperties: false
      description: Represents a KeyCloak user
    DetailedUser:
      type: object
      properties:
        projects:
          type: array
          items:
            type: string
          description: ""
          nullable: true
        id:
          type: string
          description: ""
          nullable: true
        username:
          type: string
          description: ""
          nullable: true
        enabled:
          type: boolean
          description: ""
          nullable: true
        firstName:
          type: string
          description: ""
          nullable: true
        lastName:
          type: string
          description: ""
          nullable: true
        email:
          type: string
          description: ""
          nullable: true
      additionalProperties: false
      description: Represents a user with the currently assigned projects
