version: "3.9"

services:
     
  #############################################################################################
  ###                              Seq                                                      ###
  #############################################################################################
  seq:
    image: datalust/seq
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    ports:
      - 8001:80
      - 5341:5341
    environment:
      ACCEPT_EULA: "Y"
