version: "3.7"

services:
  maltd-frontend:
    container_name: maltd-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/maltd-frontend"
      - "/node_modules"
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
