name: .NET Core Buid

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "maltd/api/src/**"
      - ".github/workflows/api-dotnet-core.yml"

jobs:
  build:
    defaults:
      run:
        working-directory: ./api/src

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
