name: .NET Core Buid

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/**"

jobs:
  build:
    defaults:
      run:
        working-directory: ./src/BcGov.Jag.AccountManagement

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.405
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
