name: Cypress Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: cypress-io/github-action@v1
        with:
          start: npm-run.sh
          wait: localhost:3000/
          browser: chrome
          headless: true
          working-directory: qa-automation/src/cypress-tests
