name: Cypress Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: cypress-io/github-action@v1
        with:
          browser: chrome
          headless: true
        working-directory: qa-automation/src/cypress-tests
      - name: Install test dependencies
        run: npm ci
        working-directory: qa-automation/src/cypress-tests
      - name: Run tests
        run: npx cypress run
        working-directory: qa-automation/src/cypress-tests
