name: Cypress Unit Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - uses: cypress-io/github-action@v1
        with:
          start: npm --prefix maltd-frontend run start
          build: npm --prefix ci
          wait: localhost:3000/
          browser: chrome
          headless: true
          working-directory: maltd-frontend
